apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-pod-deployment
  labels:
    app: user-pod-deployment
    env: dev
  namespace: vdmtest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-pod-label
      env: dev
  template:
    metadata:
      name: user-pod
      labels:
        app: user-pod-label
        env: dev
    spec:
      containers:
        - image: user-server-api:v1.0.1
          name: user-container
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: USER_SERVER_DB_USER
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: user_server_db_user
            - name: USER_SERVER_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: user_server_db_password
            - name: USER_SERVER_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: vdm-user-config-map
                  key: user_server_db_host
            - name: USER_SERVER_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: vdm-user-config-map
                  key: user_server_db_port
            - name: USER_SERVER_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: vdm-user-config-map
                  key: user_server_db_name


