apiVersion: v1
kind: Service
metadata:
  name: post-postgres-service
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: post-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432