apiVersion: v1
kind: Service
metadata:
  name: post-service
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: post-pod-label
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 5432