apiVersion: v1
kind: Service
metadata:
  name: user-postgres-service
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: user-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432