apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: user-pod-label
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081