apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-local-volume
  namespace: vdmtest
  labels:
    type: user-local
spec:
  storageClassName: user-local-volume-class
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/volume/user/data"
    type: DirectoryOrCreate